-- CreateTable
CREATE TABLE "User" (
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Word" (
    "ID" TEXT NOT NULL,
    "WORD" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Word_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Favorite" (
    "ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "WORD_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Favorite_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "History" (
    "ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "WORD_ID" TEXT NOT NULL,
    "ADDED" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "History_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_EMAIL_key" ON "User"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "Word_WORD_key" ON "Word"("WORD");

-- CreateIndex
CREATE UNIQUE INDEX "Favorite_USER_ID_WORD_ID_key" ON "Favorite"("USER_ID", "WORD_ID");

-- AddForeignKey
ALTER TABLE "Favorite" ADD CONSTRAINT "Favorite_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "User"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Favorite" ADD CONSTRAINT "Favorite_WORD_ID_fkey" FOREIGN KEY ("WORD_ID") REFERENCES "Word"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "User"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_WORD_ID_fkey" FOREIGN KEY ("WORD_ID") REFERENCES "Word"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
